name: CICD pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  compile:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build with Maven
        run: mvn compile


  security-check:
    runs-on: self-hosted
    needs: compile

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Trivy
        shell: powershell
        run: |
          $trivyVersion = "0.74.0"
          $url = "https://github.com/aquasecurity/trivy/releases/download/v$trivyVersion/trivy_${trivyVersion}_Windows-64bit.zip"
          $zip = "$env:TEMP\trivy.zip"
          $installDir = "C:\trivy"

          Invoke-WebRequest -Uri $url -OutFile $zip

          if (Test-Path $installDir) {
              Remove-Item $installDir -Recurse -Force
          }

          New-Item -ItemType Directory -Path $installDir | Out-Null
          Expand-Archive -Path $zip -DestinationPath $installDir -Force

          $env:Path += ";$installDir"

          & "$installDir\trivy.exe" --version

      - name: Trivy filesystem scan
        shell: powershell
        run: |
          trivy fs --format json -o fs-report.json .

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
